name: tic_tac_zwo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  connectivity_plus: ^6.1.3
  country_flags: ^3.2.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.16
  geolocator: ^14.0.0
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  path_provider: ^2.1.5
  supabase_flutter: ^2.8.4
  uuid: ^4.5.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_ce_generator: ^1.8.2
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/words/fallback_nouns.json

  fonts:
    - family: Onest
      fonts:
        - asset: assets/fonts/onest.extralight.ttf
        - asset: assets/fonts/onest.light.ttf
        - asset: assets/fonts/onest.thin.ttf
        - asset: assets/fonts/onest.regular.ttf

    - family: Sniglet
      fonts: 
        - asset: assets/fonts/sniglet.regular.ttf
        - asset: assets/fonts/sniglet.extrabold.ttf