name: tic_tac_zwo
description: "A tic-tac-toe game for learning German articles (der-die-das), with an additional German WÃ¶rdle mode."
publish_to: 'none'
version: 1.0.3+5

environment:
  sdk: ^3.5.4

dependencies:
  app_settings: ^6.1.1
  audioplayers: ^6.5.1
  connectivity_plus: ^6.1.3
  country_flags: ^3.2.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  flutter_slidable: ^4.0.0
  flutter_svg: ^2.0.16
  geolocator: ^14.0.0
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  supabase_flutter: ^2.8.4
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  vibration: ^3.1.4
  wiredash: ^2.5.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_ce_generator: ^1.8.2
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
    - assets/words/fallback_nouns.json
    - .env


  fonts:
    - family: Onest
      fonts:
        - asset: assets/fonts/onest.extralight.ttf
        - asset: assets/fonts/onest.regular.ttf

    - family: Sniglet
      fonts: 
        - asset: assets/fonts/sniglet.regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/images/icon_multiplatform.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"  

  image_path: "assets/images/icon_multiplatform.png"

  adaptive_icon_foreground: "assets/images/icon_multiplatform.png"
  adaptive_icon_background: "#FFFFFF"

  remove_alpha_ios: true

  min_sdk_android: 21